#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

// define('AMQP_DEBUG', true);

Eloquent\Asplode\Asplode::install();

use Icecave\Stump\Logger;
use Skewd\Amqp\ExchangeType;
use Skewd\Amqp\Message;
use Skewd\Amqp\PhpAmqpLib\PalConnector;
use Skewd\Amqp\QueueParameter;

$connector = PalConnector::create();
$connection = $connector->connect();
$channel = $connection->channel();
$queue = $channel->queue();

$message = Message::create('Hello, world!');

$queue->publish($message);

$done = false;
$queue->consume(
    function ($cm) use ($message, &$done) {
        var_dump($cm);
        // $this->assertEquals(
        //     $message,
        //     $cm->message()
        // );

        // $done = true;
    }
);

$connection->wait(1);
