#!/usr/bin/env php
<?php
require __DIR__ . '/amqp.php';

use Skewd\Amqp\ConsumerParameter;

$queue = $channel->queue('test', []);

function currentTime()
{
    static $start = null;

    if (null === $start) {
        $start = microtime(true);
    }

    return printf('%0.2f', microtime(true) - $start);
}

$queue->consume(
    function ($cm) {
        echo currentTime() . ': received ' . $cm->message()->payload() . PHP_EOL;
    },
    [ConsumerParameter::NO_ACK()]
);

$done = false;

pcntl_signal(
    SIGINT,
    function () use (&$done) {
        $done = true;
    }
);

while (!$done) {
    $connection->wait(30);
    pcntl_signal_dispatch();
}
