#!/usr/bin/env php
<?php
require __DIR__ . '/amqp.php';

use Skewd\Amqp\Connection\ConnectionWaitResult;
use Skewd\Amqp\Message;

$queue = $channel->queue('test', []);

$done = false;

pcntl_signal(
    SIGINT,
    function () use (&$done) {
        $done = true;
    }
);

$counter = 1;

while (!$done) {
    if (ConnectionWaitResult::TIMEOUT() === $connection->wait(0.001)) {
        $queue->publish(
            Message::create('Message #' . $counter++)
        );
    }

    pcntl_signal_dispatch();
}
