#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

Eloquent\Asplode\Asplode::install();

use Icecave\Stump\Logger;
use Skewd\Amqp\Connection\ConnectionWaitResult;
use Skewd\Amqp\ConsumerParameter;
use Skewd\Amqp\ExchangeType;
use Skewd\Amqp\Message;
use Skewd\Amqp\PhpAmqpLib\PalConnector;
use Skewd\Amqp\QueueParameter;

$connector  = PalConnector::create();
$connection = $connector->connect();
$channel    = $connection->channel();
$queue      = $channel->queue('test', []);

function currentTime()
{
    static $start = null;

    if (null === $start) {
        $start = microtime(true);
    }

    return printf('%0.2f', microtime(true) - $start);
}

$queue->consume(
    function ($cm) {
        echo currentTime() . ': received ' . $cm->message()->payload() . PHP_EOL;
    },
    [ConsumerParameter::NO_ACK()]
);

$done = false;

pcntl_signal(
    SIGINT,
    function () use (&$done) {
        echo PHP_EOL;
        echo currentTime() . ': exiting' . PHP_EOL;
        $done = true;
    }
);

while (!$done) {
    if (ConnectionWaitResult::SIGNAL() === $connection->wait(30)) {
        pcntl_signal_dispatch();
    }
}
