#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

Eloquent\Asplode\Asplode::install();

use Icecave\Stump\Logger;
use Skewd\Amqp\Connection\ConnectionWaitResult;
use Skewd\Amqp\ExchangeType;
use Skewd\Amqp\Message;
use Skewd\Amqp\PhpAmqpLib\PalConnector;
use Skewd\Amqp\QueueParameter;

$connector  = PalConnector::create('localhost', 5673);
$connection = $connector->connect();
$channel    = $connection->channel();
$queue      = $channel->queue('test', []);

$done = false;

pcntl_signal(
    SIGINT,
    function () use (&$done) {
        echo PHP_EOL;
        echo 'Exiting' . PHP_EOL;
        $done = true;
    }
);

$counter = 0;

while (!$done) {
    if (ConnectionWaitResult::SIGNAL() === $connection->wait(0.001)) {
        echo 'SIGNAL' . PHP_EOL;
        pcntl_signal_dispatch();
    } else {
        $counter++;

        // echo 'Publishing message #' . ++$counter . PHP_EOL;

        $queue->publish(
            Message::create('Message #' . $counter)
        );
    }
}
