#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

Eloquent\Asplode\Asplode::install();

use Icecave\Stump\Logger;
use Skewd\Amqp\ExchangeType;
use Skewd\Amqp\PhpAmqpLib\PalConnector;

$connector = PalConnector::create();
$connection = $connector->connect();
$channel = $connection->channel();

try {
    $exchange = $channel->exchange('abc', ExchangeType::FANOUT());
} catch (Exception $e) {
    echo 'Exception Code: ' . $e->getCode() . PHP_EOL;

    throw $e;
}
