#!/usr/bin/env php
<?php
// require __DIR__ . '/../vendor/autoload.php';

// Eloquent\Asplode\Asplode::install();

// use Icecave\Stump\Logger;
// use PhpAmqpLib\Channel\AMQPChannel;
// use Skewd\Common\Amqp\BasicConnectionFactory;
// use Skewd\Server\Application\Application;
// use Skewd\Server\Application\ModularApplication;
// use Skewd\Server\Application\Module;
// use Skewd\Server\Process\TickingProcess;

// // Create a standalone (not tied to a process) Skewd client ...
// $client = new StandaloneClient(new BasicConnectionFactory);

// // Create a new session ...
// $session = $client->session();

// // Get a service client for the "test-service" that is compatible
// // with version 1.0.0 ...
// $service = $client->service(
//     $session,
//     'test-service',
//     Version::parse('1.0.0')
// );

// $service->testOperation();

