#!/usr/bin/env php
<?php
require __DIR__ . '/amqp.php';

use Skewd\Lock\AmqpResourceFactory;
use Skewd\Lock\LockMode;

$factory = AmqpResourceFactory::create($connection);
$resource = $factory->createResource('test');

if (in_array('-x', $_SERVER['argv'])) {
    $mode = LockMode::EXCLUSIVE();
} else {
    $mode = LockMode::SHARED();
}

$result = false;
$lock = null;
$attempt = 0;

while (true) {
    $result = $resource->tryAcquireLock($mode, $lock);

    if ($result) {
        printf(
            'acquired %s @ %0.2f (#%d)' . PHP_EOL,
            $mode,
            microtime(true),
            ++$attempt
        );

        $lock->release();
    }
}
