#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

Eloquent\Asplode\Asplode::install();

use Icecave\Stump\Logger;
use PhpAmqpLib\Channel\AMQPChannel;
use Skewd\Application\Application;
use Skewd\Application\ModularApplication;
use Skewd\Application\Module;
use Skewd\Process\TickingProcess;

class MyModule implements Module
{
    public function name()
    {
        return 'my-module';
    }

    public function initialize(Application $application/*, AMQPChannel $channel*/)
    {
        if (rand(0, 1))
            throw new \Exception('OH SHIT!');
    }

    public function shutdown()
    {
        if (rand(0, 1))
            throw new \Exception('OH SHIT!');
    }

    public function tick()
    {
        echo '.';
        usleep(500);
        // if (rand(0, 10000) === 0)
        //     throw new \Exception('OH SHIT!');
    }
}

// -----------------------------------------------------------------------------

$logger = new Logger;
$app = new ModularApplication($logger);
$app->add(new MyModule);

$process = new TickingProcess($app, $logger);
$process->start();

