#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

Eloquent\Asplode\Asplode::install();

use Icecave\Stump\Logger;
use Skewd\Common\Amqp\AmqpNode;
use Skewd\Common\Amqp\StreamConnector;
use Skewd\Server\Application\ModularApplication;
use Skewd\Server\Process\TickingProcess;
use Skewd\Server\Session\SessionModule;

$logger = new Logger;

$app = ModularApplication::create(
    AmqpNode::create(StreamConnector::create()),
    $logger
);

$app->add(SessionModule::create());

TickingProcess::create($app, $logger)->start();

