#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

Eloquent\Asplode\Asplode::install();

use Icecave\Stump\Logger;
use Skewd\Common\Amqp\BasicConnectionFactory;
use Skewd\Common\Session\InMemorySessionStore;
use Skewd\Server\Application\ModularApplication;
use Skewd\Server\Process\TickingProcess;
use Skewd\Server\Session\SessionModule;

$sessionStore = new InMemorySessionStore;

$logger = new Logger;
$app = new ModularApplication(new BasicConnectionFactory, $logger);
$app->add(new SessionModule($sessionStore));

$process = new TickingProcess($app, $logger);
$process->start();
